apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amirrahi29/nodejs-argocd-deployment.git
    targetRevision: dev
    path: gitops/helm/chat-app
    helm: 
      valueFiles:  
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-app-main
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amirrahi29/nodejs-argocd-deployment.git
    targetRevision: main
    path: gitops/helm/chat-app
    helm:
      valueFiles:
        - values.yaml
        - values-main.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amirrahi29/nodejs-argocd-deployment.git
    targetRevision: staging
    path: gitops/helm/chat-app
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-app-uat
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amirrahi29/nodejs-argocd-deployment.git
    targetRevision: uat
    path: gitops/helm/chat-app
    helm:
      valueFiles:
        - values.yaml
        - values-uat.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: uat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
