git:
  repo_url: https://github.com/amirrahi29/nodejs-argocd-deployment.git
  platform_branch: main

azure:
  acr_name: rahicontaineregistry
  acr_login_server: rahicontaineregistry.azurecr.io
  tenant_id:
  subscription_id:
  client_id:

app:
  image_name: chat-app

helm:
  chart_path: gitops/helm/chat-app
  version: v3.14.4

aks:
  resource_group: RahiResource
  cluster_name: ChatAppCluster
